services:
  php:
    container_name: courier_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  nginx:
    container_name: courier_nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./frontend/public:/var/www/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  postgres:
    container_name: courier_postgres
    image: postgis/postgis:16-3.4-alpine
    environment:
      TZ: UTC
      POSTGRES_DB: courier_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    container_name: courier_redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
